L3-124: ETERNAL_PATH_PREFIX.
digicatapult/dscp-identity-service pull request #62
Opened 2023-04-19 12:35 UTC by n3op2

# What

Changed a prefix, to be added in the later stage, need Dave to confirm.

2023-04-21 07:07 UTC, dblane-digicatapult requested changes
This is the opposite of what was required.

The express routes being registered include `EXTERNAL_PATH_PREFIX` we need that to be removed from the route registration.

2023-04-21 15:25 UTC, dblane-digicatapult commented on app/api-v1/api-doc.js
> +      url: EXTERNAL_PATH_PREFIX ? `${url}/${EXTERNAL_PATH_PREFIX}/${API_MAJOR_VERSION}` : url,
```suggestion
      url: EXTERNAL_PATH_PREFIX ? `${url}/${EXTERNAL_PATH_PREFIX}/${API_MAJOR_VERSION}` : `${url}/${API_MAJOR_VERSION}`,
```

2023-04-21 15:44 UTC, n3op2 commented on app/api-v1/api-doc.js
> +      url: EXTERNAL_PATH_PREFIX ? `${url}/${EXTERNAL_PATH_PREFIX}/${API_MAJOR_VERSION}` : url,
updated

2023-04-24 09:07 UTC, dblane-digicatapult approved these changes

2023-04-24 09:08 UTC, merged